void main(){
  try{

    int result =12~/0;
    print("the result is $result");
  }catch(e){
    print("the exception thrown is $e");
  }
}